config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
  end

  match "/switch_account/:id" => 'admin/users#switch_account', via: 'GET'

  resources :movies do
    resources :reviews, only: [:new, :create]
  end
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  root to: 'movies#index'
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  has_many :reviews
  mount_uploader :poster_image, PosterImageUploader

  scope :search, ->(search, duration) { where("title like ? or director like ?", "%#{search}%", "%#{search}%").where("runtime_in_minutes #{duration}") }
  
  validates :title,
    presence: true

  validates :director,
    presence: true

  validates :runtime_in_minutes,
    numericality: { only_integer: true }

  validates :description,
    presence: true

  validates :poster_image_url,
    presence: true

  validates :release_date,
    presence: true

  validate :release_date_is_in_the_past

  def review_average
    reviews.sum(:rating_out_of_ten)/reviews.size if reviews.size > 0
  end

  protected

  def release_date_is_in_the_past
    if release_date.present?
      errors.add(:release_date, "should be in the past") if release_date > Date.today
    end
  end
  
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :movie

  validates :user,
    presence: true

  validates :movie,
    presence: true

  validates :text,
    presence: true

  validates :rating_out_of_ten,
    numericality: { only_integer: true }
  validates :rating_out_of_ten,
    numericality: { greater_than_or_equal_to: 1 }
  validates :rating_out_of_ten,
    numericality: { less_than_or_equal_to: 10 }
    
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :reviews, dependent: :destroy
  has_secure_password

  validates :email,
  presence: true

  validates :firstname,
  presence: true

  validates :lastname,
  presence: true

  validates :password,
  length: { in: 6..20 }, on: :create  

  def full_name
    "#{firstname} #{lastname}"
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  before_filter :admin?

  def index
    if current_user
      @users = User.all.page(params[:page]).per(10)
    else
      # flash[:notice] = "You are not an admin"
      redirect_to root_path, alert: "You are not an admin"
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to admin_users_path, notice: "#{@user.full_name} created!"
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to admin_users_path, notice: "#{@user.full_name} updated!"
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    UserMailer.user_deleted(@user).deliver
    @user.destroy
    redirect_to admin_users_path, notice: "User deleted"
  end

  def switch_account
    if sudo_user
      session[:user_id] = sudo_user.id
      session[:admin_id] = nil
      redirect_to admin_users_path
    else
      session[:admin_id] = current_user.id
      session[:user_id] = params[:id]
      redirect_to root_path
    end
  end

  private 

  def admin?
    unless current_user.admin || sudo_user.admin
      redirect_to root_path, notice: "nice try"
    end
  end

  protected

  def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :password, :password_confirmation, :admin)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  def restrict_access
    if !current_user
      flash[:alert] = "You must log in."
      redirect_to new_session_path
    end
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def sudo_user
    @sudo_user ||= User.find(session[:admin_id]) if session[:admin_id]
  end

  helper_method :current_user, :sudo_user
  
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    if params[:search]
      @movies = Movie.search(params[:search], params[:duration])
      redirect_to movies_path, notice: "Search returned no results" if @movies.empty?
    else
      @movies = Movie.all
    end
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def new
    @movie = Movie.new
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def create
    @movie = Movie.new(movie_params)

    if @movie.save
      redirect_to movies_path, notice: "#{@movie.title} was submitted successfully!"
    else
      render :new
    end
  end

  def update
    @movie = Movie.find(params[:id])

    if @movie.update_attributes(movie_params)
      redirect_to movie_path(@movie)
    else
      render :edit
    end
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    redirect_to movies_path
  end

  protected

  def movie_params
    params.require(:movie).permit(
      :title, :release_date, :director, :runtime_in_minutes, :poster_image, :remote_poster_image_url, :description
    )
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_filter :restrict_access
  before_filter :load_movie

  def new
    @review = @movie.reviews.build
  end

  def create
    @review = @movie.reviews.build(review_params)
    @review.user_id = current_user.id

    if @review.save
      redirect_to @movie, notice: "Review created successfully"
    else
      render :new
    end
  end

  protected

  def load_movie
    @movie = Movie.find(params[:movie_id])
  end

  def review_params
    params.require(:review).permit(:text, :rating_out_of_ten)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to movies_path, notice: "Welcome back, #{user.firstname}!"
    else
      flash.now[:alert] = "Log in failed..."
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to movies_path, notice: "Adios!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to movies_path, notice: "Welcome aboard, #{@user.firstname}!"
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  protected

  def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
  def formatted_date(date)
    date.strftime("%b %d, %Y")
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<%= form_for [:admin, @user] do |f| %>
  <% if @user.errors.any? %>
    <div>
      <%= pluralize(@user.errors.count, "error") %> prevented the account from being created:
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.label :firstname, "First Name" %><br>
    <%= f.text_field :firstname %>
  </div>
  <div>
    <%= f.label :lastname, "Last Name" %><br>
    <%= f.text_field :lastname %>
  </div>
  <div>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div>
    <%= f.check_box(:admin) %>
    <%= label_tag(:admin, "Admin") %>
  </div>
  <div><%= f.submit "Submit" %></div>
<% end %>

app/views/admin/users/edit.html.erb
<h1>Edit User</h1>
<%= render 'form' %>

app/views/admin/users/index.html.erb
<h1>Admin</h1>
<%= link_to "Go back", movies_path %> | <%= link_to "Create User", new_admin_user_path %>
<hr>

<%= paginate @users %>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Admin</th>
      <th>Created At</th>
      <th>Updated At</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.full_name%></td>
        <td><%= user.email %></td>
        <td><%= user.admin %></td>
        <td><%= user.created_at %></td>
        <td><%= user.updated_at %></td>
        <td><%= link_to "View", user_path(user) %> </td>
        <td><%= link_to "Edit", edit_admin_user_path(user) %></td>
        <td><%= link_to "Delete", admin_user_path(user), method: :delete, data: { confirm: "You sure dude?" } %></td>
        <% unless user == current_user %>
        <td><a href="/switch_account/<%= user.id %>">Switch</a></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<hr/>

app/views/admin/users/new.html.erb
<h1>Create User</h1>
<%= render 'form' %>

app/views/layouts/_footer.html.erb
<footer>
  <small>
    <% if current_user %>
      Signed in as <%= current_user.full_name %> (<%= link_to "Log out", session_path("current"), method: :delete %>) 
      <% if current_user.admin %>
        <%= link_to "Admin", admin_users_path %>
      <% end %>
    <% else %>
      <%= link_to "Log In", new_session_path %> | <%= link_to "Sign Up", new_user_path %>
    <% end %>
    <% if sudo_user %>
      <span><a href="/switch_account/<%= sudo_user.id %>"><%= sudo_user.full_name %></a></span>
    <% end %>
  </small>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RottenMangoes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% flash.each do |key, value| %>
    <%= content_tag(:div, value) %>
  <% end %>
  <%= yield %>
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/movies/_form.html.erb
<%= form_for @movie do |f| %>
  <% if @movie.errors.any? %>
    <div>
      <%= pluralize(@movie.errors.count, "error") %> prevented this movie from being submitted:
      <ul>
        <% @movie.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

<%= form_for @movie, html: { multipart: true } do |f| %>
  <div>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :release_date %><br>
    <%= f.date_field :release_date %>
  </div>
  <div>
    <%= f.label :director %><br>
    <%= f.text_field :director %>
  </div>
  <div>
    <%= f.label :runtime_in_minutes %><br>
    <%= f.number_field :runtime_in_minutes %>
  </div>
  <div>
    <%= f.file_field :poster_image %>
  <div>
    <%= f.label :poster_image_url %><br>
    <%= f.text_field :remote_poster_image_url %>
  </div>
  <div>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div>
    <%= f.submit "Submit" %> 
  </div>
<% end %>

app/views/movies/_movies.html.erb
<%= link_to image_tag(movie.poster_image_url(:thumb).to_s), movie_path(movie) %>
<h2><%= link_to movie.title, movie_path(movie) %> | <%= movie.review_average %>/10</h2>
<h3><%= movie.release_date %></h3>
<h4>Dir. <%= movie.director %> | <%= movie.runtime_in_minutes %> minutes</h4>
<p><%= movie.description %></p>
<hr>

app/views/movies/_reviews.html.erb
<h3>Reviews of <em><%= @movie.title %></em></h3>
<% if current_user %>
  <% @movie.reviews.each do |review| %>
    <p>Comments: <%= review.text %></p>
    <p>Rating: <%= review.rating_out_of_ten %>
    <% if review.rating_out_of_ten %>
    /10
    <% end %>
    </p>
    <small>Reviewed by- <%= link_to review.user.full_name, user_path(review.user) if review.user %></small><br/>
  <% end %>
  <p><%= link_to "Write a review!", new_movie_review_path(@movie) %></p>
<% else %>
  <p>Please <%= link_to "log in", new_session_path %> to see reviews and add your own.</p> 
<% end %>

app/views/movies/_search.html.erb
<div class="search">
  <%= form_tag(movies_path, method: "get") do %>
    <span class="form<span>-group">
      <%= text_field_tag(:search, nil, placeholder: 'Title or Director') %>
    </span>
    <span class="form-group">
    <%= select_tag "duration", options_for_select([["Under 90 minutes", "< 90"], ["Between 90 and 120 minutes", "between 90 and 120"], ["Over 120 minutes", "> 120"]]), include_blank: true %>
    </span>
    <%= submit_tag("Search") %>
  <% end %>
</div>

app/views/movies/edit.html.erb
<%= link_to "Back to this movie", movie_path(@movie) %>

<h2>Edit this movie.</h2>
<%= render 'form' %>

app/views/movies/index.html.erb
<h1>Rotten Mangoes</h1>
<%= render 'search' %>
<hr>
<%= link_to "Submit a movie!", new_movie_path %>
<hr>
<% @movies.each do |movie| %>
  <%= render partial: 'movies', locals: {movie: movie} %>
<% end %>

app/views/movies/new.html.erb
<%= link_to "Back to all movies", movies_path %>

<h2>Submit a movie!</h2>
<%= render 'form' %>

app/views/movies/show.html.erb
<%= link_to "Back to all movies", movies_path %><br/>

<%= image_tag(@movie.poster_image.to_s) %>
<h2><%= @movie.title %> (<%= link_to "edit", edit_movie_path(@movie) %>, <%= link_to "delete", movie_path(@movie), method: :delete, confirm: "You sure?" %>) | <%= @movie.review_average %>/10</h2>
<h3><%= formatted_date(@movie.release_date) %></h3>
<h4>Dir. <%= @movie.director %> | <%= @movie.runtime_in_minutes %> minutes</h4>
<p><%= @movie.description %></p>

<hr>

<%= render 'reviews' %>

app/views/reviews/_form.html.erb
<%= form_for([@movie, @review]) do |f| %>
  <% if @review.errors.any? %>
    <div>
      <%= pluralize(@review.errors.count, "error") %> prevented the review from being saved:
      <ul>
        <% @review.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label :text %><br>
    <%= f.text_area "text" %>
  </div>
  <div>
    <%= f.label :rating_out_of_ten %><br>
    <%= f.number_field :rating_out_of_ten %>
  </div>
  <div><%= f.submit "Submit" %></div>
<% end %>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/new.html.erb
<%= link_to "Back to movie", movie_path(@movie) %><br/>

<h2>Write a review of <em><%= @movie.title %></em>.</h2>

<%= render 'form' %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div>
      <%= pluralize(@user.errors.count, "error") %> prevented the account from being created:
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.label :firstname, "First Name" %><br>
    <%= f.text_field :firstname %>
  </div>
  <div>
    <%= f.label :lastname, "Last Name" %><br>
    <%= f.text_field :lastname %>
  </div>
  <div>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div><%= f.submit "Submit" %></div>
<% end %>

app/views/users/_users.html.erb
<%= link_to "Back to all movies", movies_path %><br/>
<hr/>
<h1>User Details</h1>
<div>User name: <%= @user.full_name %></div>
<div>Email: <%= @user.email %></div>

<hr/>
<h3>Reviews by <em><%= @user.full_name %></em></h3>
<% @user.reviews.each do |review| %>
  Movie: <%= link_to review.movie.title, movie_path(review.movie)%>
  <p>Review: <%= review.text %></p>
  <p>Rating: <%= review.rating_out_of_ten %>
  <% if review.rating_out_of_ten %>
  /10
  <% end %>
  </p>
  <p><small>Reviewer- <%= review.user.full_name if review.user %></small></p>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<h1>Rotten Mangoes</h1>
<hr>
<%= render 'users' %>